"""
PDF Generator - Working Version
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.colors import HexColor
from io import BytesIO
from datetime import datetime
import re

class PDFGenerator:
    
    @staticmethod
    def clean_text_for_pdf(text):
        """Remove emojis and special characters"""
        text = text.replace('**', '').replace('*', '')
        text = re.sub(r'[^\x00-\x7F]', '', text)
        text = ' '.join(text.split())
        return text
    
    @staticmethod
    def generate_notes_pdf(notes_content, video_url="", video_id=""):
        """Generate PDF from notes"""
        buffer = BytesIO()
        
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch
        )
        
        story = []
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            fontSize=20,
            textColor=HexColor('#1a1a1a'),
            spaceAfter=16,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        h2_style = ParagraphStyle(
            'H2',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=HexColor('#2c3e50'),
            spaceAfter=10,
            spaceBefore=14,
            fontName='Helvetica-Bold'
        )
        
        h3_style = ParagraphStyle(
            'H3',
            parent=styles['Heading3'],
            fontSize=12,
            textColor=HexColor('#34495e'),
            spaceAfter=8,
            spaceBefore=10,
            fontName='Helvetica-Bold'
        )
        
        normal_style = ParagraphStyle(
            'Normal',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            alignment=TA_JUSTIFY,
            spaceAfter=8
        )
        
        bullet_style = ParagraphStyle(
            'Bullet',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            leftIndent=20,
            spaceAfter=6
        )
        
        # Title
        story.append(Paragraph("AI-Generated Study Notes", title_style))
        
        # Metadata
        meta = f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
        if video_id:
            meta += f"<br/>Video ID: {video_id}"
        
        story.append(Paragraph(meta, styles['Italic']))
        story.append(Spacer(1, 20))
        
        # Process content
        lines = notes_content.split('\n')
        
        for line in lines:
            line = line.strip()
            
            if not line:
                story.append(Spacer(1, 6))
                continue
            
            clean_line = PDFGenerator.clean_text_for_pdf(line)
            
            if line.startswith('## '):
                text = clean_line.replace('##', '').strip()
                story.append(Spacer(1, 8))
                story.append(Paragraph(text, h2_style))
            
            elif line.startswith('### '):
                text = clean_line.replace('###', '').strip()
                story.append(Spacer(1, 6))
                story.append(Paragraph(text, h3_style))
            
            elif line.startswith('- ') or line.startswith('* '):
                text = clean_line.lstrip('- *').strip()
                story.append(Paragraph(f"• {text}", bullet_style))
            
            else:
                if len(clean_line) > 5:
                    story.append(Paragraph(clean_line, normal_style))
        
        # Footer
        story.append(Spacer(1, 30))
        footer = "Generated by AI-Powered YouTube Learning Platform"
        story.append(Paragraph(footer, styles['Italic']))
        
        # Build PDF
        doc.build(story)
        buffer.seek(0)
        return buffer
